### ISSUE TITLE
Issue with VPN

### ISSUE THREAD

**Issue by Mordicus** [HeroesLauncher/heroeslauncher#1]
Hi
I need to use a VPN to download and install the different games (HOTA, ERA, etc.)
But the launcher does not easily detect the system proxy settings and the download does not start.
Could you add an option to configure the proxy?
Thanks!

**Comment by HeroesLauncher** [comment]
Hi. Are you from China?
As far as I know, Github is not blocked in other countries.

Can you describe in more detail the problems with working via VPN? I myself
sometimes use warp+ vpn and there should be no problems.
As for the proxy, I’ll add a little later the ability to specify a proxy or
use a system one.

вс, 26 мая 2024 г., 5:48 Toriatama ***@***.***>:

**Comment by Mordicus** [comment]
Hello, 
Sorry for the late reply!
Yes, indeed, I am in China and Github is blocked. 
With a VPN I can visit Github website, but the launcher seems not able to find the server. I have several VPN protocol and method, like openVPN (usually works with any software) or using proxy (http=127.0.0.1 + port 16006 or 16005), but both methods fail. After many tries, I finally succeeded to start the download, but it took me a long time and many attempts and I don't know why it finally started... It does not start easily to download.

**Comment by HeroesLauncher** [comment]
I have already added proxy support, it will be in the next update 1.1.0
But there shouldn't be any problems with VPN.
