### ISSUE TITLE
cant open h3era.exe

### ISSUE THREAD

**Issue by guyKz** [HeroesLauncher/heroeslauncher#2]
after i downloaded the wog inside the homm3 folder (from gog) when i try to open the h3era.exe file it doesnt open (even from hd launcher) but the original game from hd launcher can be launched. what can i do inorder to be able to run h3era.exe ? (it didnt work with admin priv also)

**Comment by Bauaser-kun** [comment]
Hello are there any plans to make an DEP compatible update?
I move game on pendrive Between multiple devices depending on where I am know. And there is at least one device where I have no privileges to modify DEP.

**Comment by HeroesLauncher** [comment]
It’s better to ask about this in the ERA discord

чт, 27 июн. 2024 г. в 12:54, Bauaser-kun ***@***.***>:
