### ISSUE TITLE
what happened to this project?

### ISSUE THREAD

**Issue by BubbleBear** [HeroesLauncher/heroeslauncher#3]
heroes launcher hasn't been updated for days and I checked the repo, all branches and commits are deleted
what happened to this project? is there anything i can help with?

**Comment by Asmedian** [comment]
The project is developing, I am finishing the update 1.1.0
The source code has not been uploaded yet. Until it is published, I am working on the project myself. There is still a lot to do before publishing the code for collaboration.

**Comment by BubbleBear** [comment]
> The project is developing, I am finishing the update 1.1.0 The source code has not been uploaded yet. Until it is published, I am working on the project myself. There is still a lot to do before publishing the code for collaboration.

many thanks good sir! this is remarkable work indeed!
